animal = ['bear', 'python', 'peacock', 'kangaroo', 'whale', 'platypus']

print "The animal at 1 is %s." % animal[1]
print "The 3rd animal is %s." % animal[3-1]
print "The 1st animal is %s." % animal[1-1]
print "The animal at 3 is %s." % animal[3]
print "The 5th animal is %s." % animal[5-1]
print "The animal at 2 is %s." % animal[2]
print "The 6th animal is %s." % animal[6-1]
print "The animal at 4 is %s." % animal[4]
